on: push
jobs: 
  super-lint:
    run-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2
      - name: 'Run Super Linter'
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}